version: '3.8'

services:
  mongodb:
    image: mongo:latest  # Utilise l'image MongoDB officielle
    container_name: mongodb_container  # Nom du conteneur
    restart: always  # Redémarre automatiquement en cas de panne
    ports:
      - "27017:27017"  # Mappe le port 27017 de l'hôte au conteneur
    volumes:
      - mongodb_data:/data/db  # Stocke les données dans un volume persistant


volumes:
  mongodb_data: