version: '3.9'

networks:
  my_network:
    driver: bridge

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    networks:
      - my_network
    ports:
      - "27017:27017"

  simple_flask_app:
    build: .
    container_name: simple_flask_app
    restart: always
    ports:
      - "5000:5000"
    networks:
      - my_network
    environment:
      MONGO_HOST: "mongodb"
      MONGO_PORT: 27017
      MONGO_DB: "mydatabase"
    depends_on:
      - mongodb
