apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  serviceName: "mongodb"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: {{ .Values.mongodb.image }}
        ports:
        - containerPort: {{ .Values.service.ports.mongodb }}
        resources:
          requests:
            memory: {{ .Values.mongodb.resources.requests.memory }}
            cpu: {{ .Values.mongodb.resources.requests.cpu }}
          limits:
            memory: {{ .Values.mongodb.resources.limits.memory }}
            cpu: {{ .Values.mongodb.resources.limits.cpu }}
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.mongodb.storage }}

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: womri
spec:
  clusterIP: None  # Service headless
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: {{ .Values.service.ports.mongodb }}
    targetPort: {{ .Values.service.ports.mongodb }}
