apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mongodb-access-policy
  namespace: womri
spec:
  podSelector:
    matchLabels:
      app: mongodb
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: webdb
    ports:
    - protocol: TCP
      port: 27017
