---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdb
  labels:
    app: webdb
spec:
  replicas: {{ .Values.webdb.replicas }}
  selector:
    matchLabels:
      app: webdb
  template:
    metadata:
      labels:
        app: webdb
    spec:
      containers:
      - name: webdb
        image: {{ .Values.webdb.image }}
        ports:
        - containerPort: {{ .Values.webdb.service.port }}
        env:
        - name: MONGO_HOST
          valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: mongoHost
        - name: MONGO_PORT
          valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: mongoPort
---
apiVersion: v1
kind: Service
metadata:
  name: webdb
spec:
  selector:
    app: webdb
  ports:
  - protocol: TCP
    port: {{ .Values.webdb.service.port }}
    targetPort: {{ .Values.webdb.service.port }}
  type: ClusterIP