version: '3.9'

networks:
  my_network:
    driver: bridge

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container_4
    networks:
      - my_network
    ports:
      - "27017:27017"

  flask_with_db:
    build:
      context: .
    container_name: flask_with_db
    networks:
      - my_network
    volumes:
      - .:/app
    environment:
      MONGO_HOST: "mongodb"
      MONGO_PORT: 27017
      MONGO_DB: "mydatabase"
    command: python app_with_db.py
    depends_on:
      - mongodb

  flask_without_db:
    build:
      context: .
    container_name: flask_without_db
    networks:
      - my_network
    volumes:
      - .:/app
    command: python app_without_db.py

  nginx:
    image: nginx:latest
    container_name: nginx_load_balancer
    ports:
      - "80:80"
    networks:
      - my_network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask_with_db
      - flask_without_db
